version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-local
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@55w0rd
      - POSTGRES_DB=todo
