spring:
  data:
    rest:
      basePath: /api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/todo?currentSchema=todo"
    username: "user"
    password: "P@55w0rd"
    hikari:
      minimumIdle: 5
      maximumPoolSize: 21
      autoCommit: false
      connection-timeout: 1000
      pool-name: "hikari-pool"
    flyway:
      enabled: false
      locations: classpath:db/migration/dev
      url: "jdbc:postgresql://localhost:5432/todo"
      user: "user"
      password: "P@55w0rd"
      connect-retries: 3
      schemas: "todo"
  sql:
    init:
      enabled: on
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    groups:
      enabled: true
